spring:
  application:
    name: spring-cloud-eureka
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #本地
    username: root
    password: 123456abcD.
    url: jdbc:mysql://localhost:3306/ISP_DB?characterEncoding=utf-8&useSSL=false
    
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non-null
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  port: 10020
  context-path: /quickQuery

